#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Application\Command\Issues;
use Application\Command\Jira;
use Application\Command\Users;
use Application\Config;
use Colibri\Console\Application;

Config::setBaseDir(__DIR__ . '/config');

exit(
    (new Application('YouTrack <-> Jira integration', 'dev'))
    ->setLogo('               _____                _       __   __     __  _           
/\_/\___  _   /__   \_ __ __ _  ___| | __  / /___\ \    \ \(_)_ __ __ _ 
\_ _/ _ \| | | |/ /\/ \'__/ _` |/ __| |/ / / /_____\ \    \ \ | \'__/ _` |
 / \ (_) | |_| / /  | | | (_| | (__|   <  \ \_____/ / /\_/ / | | | (_| |
 \_/\___/ \__,_\/   |_|  \__,_|\___|_|\_\  \_\   /_/  \___/|_|_|  \__,_|
')
    ->addCommands([
        new Issues\Show(),
        new Issues\Count(),
        new Issues\Copy(),
        new Jira\IssueTypes(),
        new Jira\Assignees(),
        new Users\Show(),
    ])
    ->run()
);
